### PR TITLE
Bank Letter: Add English template & flexible generation

### PR DESCRIPTION
**Pull request by Herrie82**
Allow for both German (de) and English (en) initialization letters.

Signed-off-by: Herman van Hazendonk <github.com@herrie.org>

### CODE REVIEW

**Comment by nanov** [comment]
Great and absolutely needed work!

Will land in next release, and I'm taking taking the liberty to add you to the contributors list.

**Comment by Herrie82** [comment]
@nanov Well I'm just trying to contribute my bits. Working with a small bank in Luxembourg to get things working. There are many paid solutions out there, but for our need a free solution would suffice (just to pull MT94X and CAMT05x statements). So I will try to contribute what I can. I prefer NodeJS over the Java/Rails versions out there, since I'm a lot more familiar with (Node)JS ;)

**Comment by nanov** [comment]
I am happy to hear that, let us know if you need any help! Once you got it working with the bank it would be cool to add it to the supported banks list.

**Comment by Herrie82** [comment]
@nanov INI and pulling bank keys went OK. Now trying to figure out how to pull VMK, STA or DKI. Any examples or guidance you could share?

**Comment by nanov** [comment]
Well something like this should get you going :
```js
'use strict';

const ebics = require('../index');

const client = new ebics.Client({
	url: 'https://ebics.server',
	partnerId: '',
	userId: '',
	hostId: '',
	passphrase: 'test', // keys-test will be decrypted with this passphrase
	keyStorage: ebics.fsKeysStorage('./keys-test'),
});

// The bank keys must have been already saved
client.send(ebics.Orders.STA('2018-01-01', '2019-11-25')) // startDate, endDate
	.then((resp) => {
		console.log('Response for STA order %j', resp);
		if (resp.technicalCode !== '000000')
			throw new Error('Something went wrong');

                 // parsing the MT940 file should happen somewhere here, ideally after saving it to disk
		const data = Buffer.from(resp.orderData);
		console.log(data.toString('utf8'));
	})
	.catch((err) => {
		console.error(err);
		process.exit(1);
	});
```

Please let me know if this works for you.

**Comment by Herrie82** [comment]
@nanov I tried without the dates before and that seems to have caused my issues. Now it works slightly better, but not getting anything yet, though bank confirmed there should be some STA available.

(node:4864) [DEP0106] DeprecationWarning: crypto.createDecipher is deprecated.
Response for STA order {"orderData":{},"orderId":"","technicalCode":"000000","technicalCodeSymbol":"[EBICS_OK] OK","technicalCodeShortText":"OK","technicalCodeMeaning":"No technical errors occurred during processing of the EBICS request","businessCode":"090003","businessCodeSymbol":"EBICS_AUTHORISATION_ORDER_TYPE_FAILED","businessCodeShortText":"The subscriber is not entitled to submit orders of the selected order type"}
TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type object
    at Function.from (buffer.js:305:9)
    at C:\node_modules\ebics-client\examples\get-STA2.js:24:23
    at processTicksAndRejections (internal/process/task_queues.js:93:5) {
  code: 'ERR_INVALID_ARG_TYPE'
}

Any thoughts on what might be the issue?

**Comment by nanov** [comment]
> [EBICS_OK] OK","technicalCodeShortText":"OK","technicalCodeMeaning":"No technical errors occurred during processing of the EBICS request","businessCode":"090003","businessCodeSymbol":"EBICS_AUTHORISATION_ORDER_TYPE_FAILED","businessCodeShortText":"The subscriber is not entitled to submit orders of the selected order type"}

this seems to be your problem, this is the response you get from the bank.

**Comment by Herrie82** [comment]
@nanov Yeah it seems like they didn't setup my permissions for VMK/STA and DKI (DKI is not supported yet, I know, but will try to add that with a PR once I get things working ;)). I checked with the bank and they said they setup my permissions correctly, so that's confusing me a bit right now.

**Comment by nanov** [comment]
@Herrie82 sometimes the ones you're speaking with the bank are not exactly technical people and some confusion happens, I would try the Z53 order type strictly for information and then get with my results to the bank.

**Comment by Herrie82** [comment]
@nanov Well this should be their "EBICS"-guy ;) I just sent HTD and that seems to confirm they did something wrong:
`
    <UserInfo>
        <UserID Status="1">HermanVH</UserID>
        <Name>HERMAN VAN HAZENDONK</Name>
        <Permission>
            <OrderTypes>HAA HKD HPB HPD HTD</OrderTypes>
        </Permission>
        <Permission AuthorisationLevel="T">
            <OrderTypes>HCA HCS HIA INI PUB SPR</OrderTypes>
        </Permission>
    </UserInfo>
`

**Comment by nanov** [comment]
@Herrie82 not uncommon :/

**Comment by Herrie82** [comment]
@nanov Yeah, HKD also worked, so sent them an extract of the other users who do have the correct credentials. Let's see if they fix it ;)

**Comment by Herrie82** [comment]
@nanov They "fixed something" and now stuff works ;)

**Pull request merged**
