### PR TITLE
Add Z53 order type

### PR DESCRIPTION
**Pull request by anandsahil**
The idea behind this PR is to add Z53 i.e CAMT53 file order type.

Also i extracted the dateRange function to constants as it was repeated same across multiple files.

### CODE REVIEW

**Comment by nanov** [comment]
Looks good in general, just a one thing:

Could you create a deicated ```utils.js``` file/directory and move the ```dateRange``` function to there? I would like to keep the constants file as clean and not pollute it with functions ( which are not constants. ).

**Comment by anandsahil** [comment]
> Looks good in general, just a one thing:
> 
> Could you create a deicated `utils.js` file/directory and move the `dateRange` function to there? I would like to keep the constants file as clean and not pollute it with functions ( which are not constants. ).

sure i will  do that

**Comment by nanov** [comment]
Merged, will land in npm later.

**Comment by nanov** [comment]
landed in 0.0.7, thank you!

**Pull request merged**
